[project]
name = "yokogawa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyusb>=1.3.1",
    "pyvisa>=1.16.1",
    "pyvisa-py>=0.8.1",
]
